### ISSUE TITLE
WDL function length() is not handled

### ISSUE THREAD

**Issue by dinithiW** [common-workflow-lab/wdl-cwl-translator#60]
Currently, the WDL function length() is not translated by the convertor. (https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#int-lengtharrayx)

A WDL workflow containing length() function can be found here. (https://github.com/biowdl/tasks/blob/develop/bcftools.wdl#L75)

**Comment by Th3nn3ss** [comment]
No. Still searching through the CWL user guide. There seems to be no mention of `length` and I am currently looking through the `Array Inputs` section.

**Comment by mr-c** [comment]
> There seems to be no mention of `length`

Yeah, you'll need to use a CWL Expression (javascript) again: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/length

Using https://github.com/biowdl/tasks/blob/68c56c9f7cceab1658dfae39f8d130d8ee4fe71a/bcftools.wdl#L75 as an example:
The WDL Expression Placeholder
``` wdl
~{true="--samples" false="" length(samples) > 0}
```
should look something like this in CWL (untested, though)
``` cwl
${if (inputs.samples.length > 0) {return "--samples";} else {return "";}}
```

**Comment by Th3nn3ss** [comment]
Can I get examples for when the length() function appears by itself without being associated with `true` and `false` keywords?

And how can I source for these examples myself?

**Comment by Th3nn3ss** [comment]
Am trying to run tests for the feature I implemented but am getting an error with token recognition. Am using this workflow https://github.com/biowdl/tasks/blob/develop/bcftools.wdl#L75
![Screenshot from 2021-10-15 18-03-06](https://user-images.githubusercontent.com/25160953/137525962-1e1d7eb5-8666-4eb1-9aa8-c9230a8bb48b.png)

**Comment by mr-c** [comment]
> Am trying to run tests for the feature I implemented but am getting an error with token recognition. Am using this workflow https://github.com/biowdl/tasks/blob/develop/bcftools.wdl#L75
> ![Screenshot from 2021-10-15 18-03-06](https://user-images.githubusercontent.com/25160953/137525962-1e1d7eb5-8666-4eb1-9aa8-c9230a8bb48b.png)
> 

Can you open a draft PR? That will be easier for me to diagnose

**Comment by Th3nn3ss** [comment]
> Could be a key error. There's no key `Array[String]` in the dictionary `wdl_type` defined at the beginning of main.py. https://github.com/common-workflow-lab/wdl-cwl-translator/blob/main/wdl2cwl/main.py#L23 Try commenting the inputs of type `Array[String]` in the inputs and command sections of bcftools.wdl and see whether the error still persists.

Tried commenting some all `Array[String]`. Now the error is 
`Traceback (most recent call last):
  File "wdl2cwl/main.py", line 798, in <module>
    main()
  File "wdl2cwl/main.py", line 794, in main
    result.write(str(convert(args.workflow)))
  File "wdl2cwl/main.py", line 586, in convert
    cwl_inputs = get_input(cwl_inputs, ast.task_inputs, ast.task_inputs_bound)
  File "wdl2cwl/main.py", line 515, in get_input
    input_value = int(raw_input_value)
ValueError: invalid literal for int() with base 10: '1+ceil(size(inputFile,G))'
`

**Comment by mr-c** [comment]
> Could be a key error. There's no key `Array[String]` in the dictionary `wdl_type` defined at the beginning of main.py.
> https://github.com/common-workflow-lab/wdl-cwl-translator/blob/main/wdl2cwl/main.py#L23

Why not add `"Array[String]": "string[]"`?

**Comment by Th3nn3ss** [comment]
> > Could be a key error. There's no key `Array[String]` in the dictionary `wdl_type` defined at the beginning of main.py.
> > https://github.com/common-workflow-lab/wdl-cwl-translator/blob/main/wdl2cwl/main.py#L23
> 
> Why not add `"Array[String]": "string[]"`?

I have added that to the main.py and now am getting this error 
![Screenshot from 2021-10-16 11-28-06](https://user-images.githubusercontent.com/25160953/137583964-e19735fa-ebde-49ed-899a-203f601821d9.png)

Please let me know if there's a better way I can report errors rather than sending screenshots here.

**Comment by mr-c** [comment]
> Please let me know if there's a better way I can report errors rather than sending screenshots here.

Can you copy and paste from your terminal surrounded by triple backticks on an empty line?

Example:
<pre>
```
$ test
results
```
</pre>

Becomes

```
$ test
results
```

**Comment by mr-c** [comment]
> It's referencing a file that's not in the directory.


Please `git pull https://github.com/common-workflow-lab/wdl-cwl-translator.git main` and then `make install-dep`
